---
title: "Publications"
# description: |
#   A showcase of distill websites and blogs. Add yours [here](https://github.com/jhelvy/distillery)!
output:
  distill::distill_article:
    toc: true
# base_url: https://distillery.rbind.io
# preview: images/distillery.png
params:
  update_all: FALSE
  check_url: FALSE
---
Dr. Jane Disney received a B.S. in Biology and an M.S. in Genetics from Penn State University and a Ph.D. in Zoology from Washington State University. She is currently the Research Training Director and PI of an NSF REU grant at MDI Biological Laboratory. In addition, she is a senior staff scientist and directs the activities of the Community Environmental Health Laboratory. She is the co-developer of the citizen science online data portal, Anecdata.org. Since 2000, she has worked with multiple community partners, identifying and helping to remedy threats to public health and the clean waters on and around Mount Desert Island. Community Environmental Health Laboratory projects include participation in state level initiatives such as the Maine Healthy Coastal Beaches and Maine Volunteer Phytoplankton Monitoring programs and an NIH/NIGMS Science Education Partnership Award (SEPA) project that involves partnering scientists with teachers and students in collecting well water samples for arsenic analysis. Dr. Disney and her Community Environmental Health Laboratory staff have engaged dozens of summer research fellows at the undergraduate and high school level and thousands of citizen scientists, including teachers, students, and community members in these and other projects over the last two decades.


### 2022

Erickson OA, Cole RB, Isaacs JM, Alvarez-Clare S, Arnold J, Augustus-Wallace A, Ayoob JC, Berkowitz A, Branchaw J, Burgio KR, Cannon CH, Ceballos RM, Cohen CS, Coller H, Disney J, Doze VA, Eggers MJ, Farina S, Ferguson EL, Gray JJ, Greenberg JT, Hoffmann A, Jensen-Ryan D, Kao RM, Keene AC, Kowalko JE, Lopez SA, Mathis C, Minkara M, Murren CJ, Ondrechen MJ, Ordoñez P, Osano A, Padilla-Crespo E, Palchoudhury S, Qin H, Ramírez-Lugo J, Reithel J, Shaw CA, Smith A, Smith R, Summers AP, Tsien F, Dolan EL. "How Do We Do This at a Distance?!" A Descriptive Study of Remote Undergraduate Research Programs during COVID-19. CBE Life Sci Educ. 2022 Mar;21(1):ar1. doi: 10.1187/cbe.21-05-0125. PMID: 34978923 

### 2021
Babich R, Craig E, Muscat A, Disney J, Farrell A, Silka L, Jayasundara N. Defining drinking water metal contaminant mixture risk by coupling zebrafish behavioral analysis with citizen science. Sci Rep. 2021 Aug 27;11(1):17303. doi: 10.1038/s41598-021-96244-4. PMID: 34453073; PMCID: PMC8397788.

Farrell A, Buckman K, Hall SR, Muñoz I, Bieluch K, Zoellick B, Disney J. Adaptations to a Secondary School-Based Citizen Science Project to Engage Students in Monitoring Well Water for Arsenic during the COVID-19 Pandemic. J STEM Outreach. 2021 Jul;4(2):10.15695/jstem/v4i2.05. doi: 10.15695/jstem/v4i2.05. Epub 2021 Jul 19. PMID: 34532651; PMCID: PMC8442737.

Bailey C, Farrell A, Purty T, Taylor A, Disney J. Development of Privacy Features on Anecdata.org, a Free Citizen Science Platform for Collecting Datasets for Climate Change and Related Projects. Front Clim. 2021 Apr;3:620100. doi: 10.3389/fclim.2021.620100. Epub 2021 Apr 30. PMID: 34541525; PMCID: PMC8444998.

### Earlier work

Stanton BA, Caldwell K, Congdon CB, Disney J, Donahue M, Ferguson E, Flemings E, Golden M, Guerinot ML, Highman J, James K, Kim C, Lantz RC, Marvinney RG, Mayer G, Miller D, Navas-Acien A, Nordstrom DK, Postema S, Rardin L, Rosen B, SenGupta A, Shaw J, Stanton E, Susca P. MDI Biological Laboratory Arsenic Summit: Approaches to Limiting Human Exposure to Arsenic. Curr Environ Health Rep. 2015 Sep;2(3):329-37. doi: 10.1007/s40572-015-0057-9.


Disney JE,Fox EL, Farrell A, LeDuc C, Bailey C. Engagement in marine conservation through citizen science: A community-based approach to eelgrass restoration in Frenchman Bay, Maine, USA. Citizen Science for Coastal and Marine Conservation. 2017.


Disney JE, Cait Bailey,  Anna Farrell,  Ashley Taylor. Next Generation Citizen Science Using Anecdata.org. Maine Policy Review. Jan 2017.

J. Disney, C. Bailey, A. Farrell, A. Taylor and B. McGreavy, "Anecdata.org: An online citizen science platform for Building Climate Resilient Communities," OCEANS 2018 MTS/IEEE Charleston, 2018, pp. 1-4, doi: 10.1109/OCEANS.2018.8604515.

C. Bailey, J. Disney, A. Farrell and A. Taylor, "Anecdata.org: Data collection with the power of the crowd," OCEANS 2018 MTS/IEEE Charleston, 2018, pp. 1-5, doi: 10.1109/OCEANS.2018.8604652.

Cait Bailey  Jane Disney. Anecdata: collecting observations of a changing world. F1000Research. 26 Feb 2015

Biodegradable Grids: An Effective Method for Eelgrass (Zostera marina) Restoration in Maine. George W. Kidder  Shannon White  Molly F. Miller  Wendy S. Norden  Theodore Taylor  Jane Disney. Journal of Coastal Research.  Nov 2013

George W. Kidder  Jane Disney  Molly F. Miller. Biodegradable grids enhance success of eelgrass restoration in Maine. F1000Research.  08 Nov 2012

Disney JE, Johnson KR, Magnuson NS, Sylvester SR, Reeves R. High-mobility group protein HMG-I localizes to G/Q- and C-bands of human and mouse chromosomes. J Cell Biol. 1989 Nov;109(5):1975-82. doi: 10.1083/jcb.109.5.1975. PMID: 2808516; PMCID: PMC2115878.

